using System.Reflection;

// NB! this file is automatically generated. All manual changes will be lost on build.
// Check ~/_tools/Nortal.Utilities.AssemblyVersioning.props file for other available algorithms and supported attributes.

// Generated based on assembly version: 0.9.1.0
[assembly: AssemblyInformationalVersion("0.9.1-Debug-20140502-0857")] // algorithm: NugetSemanticVersionGenerator
[assembly: AssemblyConfiguration("Debug (on UTC2014-05-02T08:57:34 by erik at ERIK-PC)")] // algorithm: HumanReadableBuildInfoGenerator
